-- 喵宇宙数据库初始化脚本
-- Miao Universe Database Initialization Script

-- 创建 cats 表
-- Create cats table
create table if not exists public.cats (
  id bigint generated by default as identity not null,
  name character varying not null,
  breed character varying null,
  age smallint null,
  sex smallint null, -- 1=公(male), 2=母(female), 0=未知(unknown)
  description text null,
  tags character varying null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp without time zone null default now(),
  constraint cat_pkey primary key (id)
) tablespace pg_default;

-- 创建索引
-- Create indexes
create index if not exists idx_cats_created_at on public.cats(created_at desc);
create index if not exists idx_cats_name on public.cats(name);

-- 插入示例数据
-- Insert sample data
insert into public.cats (name, breed, age, sex, description, tags)
values
  ('小橘', '橘猫', 2, 1, '性格温顺，喜欢晒太阳，对小鱼干没有抵抗力。是个不折不扣的吃货，看见食物就会喵喵叫。', '温顺,亲人,吃货'),
  ('雪球', '英国短毛猫', 1, 2, '优雅的小公主，毛色雪白纯净，眼睛是漂亮的蓝色。喜欢安静的环境，偶尔会高冷。', '优雅,安静,高冷'),
  ('虎斑', '美国短毛猫', 3, 1, '活力十足的运动健将，喜欢爬高上低，对逗猫棒和激光笔非常感兴趣。', '活泼,好动,爱玩'),
  ('布丁', '布偶猫', 1, 2, '拥有深蓝色的眼睛和柔软的长毛，性格温柔体贴，是完美的陪伴型猫咪。', '温柔,粘人,颜值高'),
  ('黑炭', '黑猫', 4, 1, '全身乌黑发亮，眼睛在黑暗中会发出神秘的绿光。性格独立，但对主人非常忠诚。', '独立,忠诚,神秘'),
  ('奶茶', '暹罗猫', 2, 2, '拥有独特的重点色花纹和蓝宝石般的眼睛。性格活泼，喜欢与人交流，叫声独特。', '活泼,健谈,聪明')
on conflict do nothing;

-- 设置 RLS (Row Level Security) 策略
-- Set up RLS policies
alter table public.cats enable row level security;

-- 允许所有人读取
-- Allow everyone to read
create policy "Allow public read access"
  on public.cats
  for select
  using (true);

-- 允许所有人插入（实际部署时应该限制）
-- Allow everyone to insert (should be restricted in production)
create policy "Allow public insert access"
  on public.cats
  for insert
  with check (true);

-- 允许所有人更新（实际部署时应该限制）
-- Allow everyone to update (should be restricted in production)
create policy "Allow public update access"
  on public.cats
  for update
  using (true);

-- 允许所有人删除（实际部署时应该限制）
-- Allow everyone to delete (should be restricted in production)
create policy "Allow public delete access"
  on public.cats
  for delete
  using (true);

-- ============================================
-- Supabase Storage 配置
-- Supabase Storage Configuration
-- ============================================

-- 注意：以下 SQL 需要在 Supabase Dashboard 中手动执行
-- Note: The following operations need to be done manually in Supabase Dashboard

-- 1. 创建 Storage Bucket (通过 UI 或 SQL)
-- 1. Create Storage Bucket (via UI or SQL)
--
-- 在 Supabase Dashboard > Storage > 点击 "New bucket"
-- 名称: cat-photos
-- Public: 勾选 (允许公开访问)
--
-- 或者执行以下 SQL:
-- insert into storage.buckets (id, name, public)
-- values ('cat-photos', 'cat-photos', true);

-- 2. 设置 Storage 策略
-- 2. Set up Storage policies
--
-- 在 Storage 设置中添加策略，或执行以下 SQL:
--
-- create policy "Public Access"
--   on storage.objects for all
--   using (bucket_id = 'cat-photos');
--
-- create policy "Public Upload"
--   on storage.objects for insert
--   with check (bucket_id = 'cat-photos');

-- ============================================
-- 完成提示
-- Completion message
-- ============================================

-- 执行完成后，你应该能看到：
-- After execution, you should see:
-- 1. cats 表已创建，包含 6 条示例数据
-- 1. cats table created with 6 sample records
-- 2. 相关索引已创建
-- 2. Related indexes created
-- 3. RLS 策略已启用
-- 3. RLS policies enabled
--
-- 接下来需要手动配置 Storage bucket
-- Next, manually configure Storage bucket in Dashboard
