-- =====================================================
-- 喵宇宙数据库建表脚本
-- =====================================================
-- 在 Supabase Dashboard > SQL Editor 中执行此脚本
-- 创建所有必需的表和配置

-- =====================================================
-- 1. 创建 cats 表
-- =====================================================

-- 删除旧表（如果需要重新创建）
-- DROP TABLE IF EXISTS public.cats CASCADE;

-- 创建 cats 表
CREATE TABLE IF NOT EXISTS public.cats (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name character varying NOT NULL,
  breed character varying NULL,
  age numeric NULL,
  sex smallint NULL,
  description text NULL,
  tags character varying NULL,
  images text[] NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT cats_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- 添加表注释
COMMENT ON TABLE public.cats IS '猫咪信息表';

-- 添加字段注释
COMMENT ON COLUMN public.cats.id IS '猫咪唯一标识';
COMMENT ON COLUMN public.cats.name IS '猫咪名字';
COMMENT ON COLUMN public.cats.breed IS '品种';
COMMENT ON COLUMN public.cats.age IS '年龄（岁）';
COMMENT ON COLUMN public.cats.sex IS '性别：1=公，2=母';
COMMENT ON COLUMN public.cats.description IS '描述';
COMMENT ON COLUMN public.cats.tags IS '标签（逗号分隔）';
COMMENT ON COLUMN public.cats.images IS '图片 URL 数组（来自 Supabase Storage）';
COMMENT ON COLUMN public.cats.created_at IS '创建时间';
COMMENT ON COLUMN public.cats.updated_at IS '更新时间';

-- =====================================================
-- 2. 配置 RLS (Row Level Security) 策略
-- =====================================================

-- 启用 RLS
ALTER TABLE public.cats ENABLE ROW LEVEL SECURITY;

-- 删除旧策略（如果存在）
DROP POLICY IF EXISTS "Allow public read access" ON public.cats;
DROP POLICY IF EXISTS "Allow public insert access" ON public.cats;
DROP POLICY IF EXISTS "Allow public update access" ON public.cats;
DROP POLICY IF EXISTS "Allow public delete access" ON public.cats;

-- 允许所有人读取
CREATE POLICY "Allow public read access"
ON public.cats
FOR SELECT
TO public
USING (true);

-- 允许所有人插入
CREATE POLICY "Allow public insert access"
ON public.cats
FOR INSERT
TO public
WITH CHECK (true);

-- 允许所有人更新
CREATE POLICY "Allow public update access"
ON public.cats
FOR UPDATE
TO public
USING (true)
WITH CHECK (true);

-- 允许所有人删除
CREATE POLICY "Allow public delete access"
ON public.cats
FOR DELETE
TO public
USING (true);

-- =====================================================
-- 3. 创建索引（提高查询性能）
-- =====================================================

-- 在 name 字段上创建索引（方便按名字搜索）
CREATE INDEX IF NOT EXISTS idx_cats_name ON public.cats USING btree (name);

-- 在 breed 字段上创建索引（方便按品种筛选）
CREATE INDEX IF NOT EXISTS idx_cats_breed ON public.cats USING btree (breed);

-- 在 created_at 字段上创建索引（方便按时间排序）
CREATE INDEX IF NOT EXISTS idx_cats_created_at ON public.cats USING btree (created_at DESC);

-- =====================================================
-- 4. 插入示例数据（可选）
-- =====================================================

-- 清空旧数据（谨慎使用）
-- TRUNCATE TABLE public.cats RESTART IDENTITY CASCADE;

-- 插入示例猫咪数据
INSERT INTO public.cats (name, breed, age, sex, description, tags, images)
VALUES
  (
    '小橘',
    '橘猫',
    2,
    1,
    '性格温顺，喜欢晒太阳，对小鱼干没有抵抗力。是个不折不扣的吃货，看见食物就会喵喵叫。',
    '温顺,亲人,吃货',
    ARRAY['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=500&h=400&fit=crop']
  ),
  (
    '雪球',
    '英国短毛猫',
    1,
    2,
    '优雅的小公主，毛色雪白纯净，眼睛是漂亮的蓝色。喜欢安静的环境，偶尔会高冷。',
    '优雅,安静,高冷',
    ARRAY['https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=500&h=400&fit=crop']
  ),
  (
    '虎斑',
    '美国短毛猫',
    3,
    1,
    '活力十足的运动健将，喜欢爬高上低，对逗猫棒和激光笔非常感兴趣。',
    '活泼,好动,爱玩',
    ARRAY['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500&h=400&fit=crop']
  ),
  (
    '布丁',
    '布偶猫',
    1,
    2,
    '拥有深蓝色的眼睛和柔软的长毛，性格温柔体贴，是完美的陪伴型猫咪。',
    '温柔,粘人,颜值高',
    ARRAY['https://images.unsplash.com/photo-1529778873920-4da4926a72c2?w=500&h=400&fit=crop']
  ),
  (
    '黑炭',
    '黑猫',
    4,
    1,
    '全身乌黑发亮，眼睛在黑暗中会发出神秘的绿光。性格独立，但对主人非常忠诚。',
    '独立,忠诚,神秘',
    ARRAY['https://images.unsplash.com/photo-1494256997604-768d1f608cac?w=500&h=400&fit=crop']
  ),
  (
    '奶茶',
    '暹罗猫',
    2,
    2,
    '拥有独特的重点色花纹和蓝宝石般的眼睛。性格活泼，喜欢与人交流，叫声独特。',
    '活泼,健谈,聪明',
    ARRAY['https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=500&h=400&fit=crop']
  )
ON CONFLICT (id) DO NOTHING;

-- =====================================================
-- 5. 验证数据
-- =====================================================

-- 查看所有猫咪
SELECT
  id,
  name,
  breed,
  age,
  CASE
    WHEN sex = 1 THEN '公'
    WHEN sex = 2 THEN '母'
    ELSE '未知'
  END as gender,
  description,
  tags,
  array_length(images, 1) as image_count,
  created_at
FROM public.cats
ORDER BY id;

-- 查看表结构
SELECT
  column_name,
  data_type,
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'cats'
ORDER BY ordinal_position;

-- 查看 RLS 策略
SELECT
  schemaname,
  tablename,
  policyname,
  permissive,
  roles,
  cmd,
  qual
FROM pg_policies
WHERE schemaname = 'public'
  AND tablename = 'cats';

-- =====================================================
-- 完成！
-- =====================================================
--
-- 下一步：
-- 1. 配置 Storage Bucket（如果还没有）
--    - 在 Dashboard > Storage 中创建 cat-images bucket
--    - 勾选 Public bucket
--
-- 2. 配置 Storage 策略
--    - 执行 setup-storage.sql 脚本
--
-- 3. 测试应用
--    - 打开 index.html
--    - 应该能看到 6 只示例猫咪
--    - 尝试编辑和上传图片
--
-- =====================================================
